server:
  port: 8761

eureka:
  instance:
    hostname: eurekaregistry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
---

spring:
  profiles: local
eureka:
  instance:
    hostname: localhost